Redesign Environment API
entity-neural-network/incubator pull request #166
Opened 2022-01-30 07:12 UTC by cswinter

2022-01-31 16:22 UTC, Bam4d requested changes
Overall the new API makes more sense. 

We split out the IDS into entity types... but why don't we just put the IDS along with the entities in the features? Having the same place for both things is more coherent and much easier to debug e.g:

```
features={"box": {"id": ..., "features": [a,b,c,d,e] ....}
```
It still looks like the ordering of the IDs in the ``ids`` property is down to the environment designer, which is what I think we were aiming to avoid?

Other notes:
I made a few minor comments here and there that I found when playing with the branch.

I changed some of the tests to check that the order of the entity IDs does not effect indexing.

2022-01-31 16:54 UTC, cswinter commented
> We split out the IDS into entity types... but why don't we just put the IDS along with the entities in the features? Having the same place for both things is more coherent and much easier to debug e.g:

I think we could do this, I actually started out combining all of "actions", "ids", and "features" into a single `EntityObs` so we have a single `entities: Mapping[EntityType, EntityObs]`, but then changed back to the previous scheme since it made it harder to figure out all the algorithmic changes. I think it probably makes sense to still keep `actions` separate, since actions feel like a top-level object and often don't make sense to split across entity type, but joining ids and entities seems good. Maybe we could also have a constructor/function on `Environment` which you pass just the lists of ids and features, and it does the whole `np.array(...` thing and validates that the number of features match and the number of ids match the number of entities.

2022-02-02 04:28 UTC, cswinter commented on entity_gym/TUTORIAL.md
> +            ids={
I think at least mypy should complain.

2022-02-02 04:33 UTC, cswinter commented
@Bam4d made a bunch of fixes and also added a new `Observation.from_entity_obs` method that allows specifying ids and features side-by-side in the same dict.

2022-02-02 04:35 UTC, cswinter commented
It's also completely optional to use `np.array`, so you don't need to think about the right shape for empty arrays or dtype.

2022-02-02 11:08 UTC, Bam4d commented
Ill review this by doing the necessary Griddly changes and seeing if I run into any issues!

2022-02-02 12:12 UTC, Bam4d commented
going to try get released today so we can build and test with poetry etc... https://github.com/Bam4d/Griddly/pull/165/files

2022-02-02 16:51 UTC, Bam4d approved these changes

2022-02-04 02:42 UTC, cswinter commented
@Bam4d Thanks for the fixes!

2022-02-04 02:42 UTC, merged